-- Δημιουργία της βάσης δεδομένων
DROP DATABASE IF EXISTS HOTEL_DB;
CREATE DATABASE HOTEL_DB;
USE HOTEL_DB;

-- Πίνακας Πελατών
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
    CUSTOMER_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    PRIMARY KEY (CUSTOMER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Πίνακας Διαχειριστών
DROP TABLE IF EXISTS ADMIN;
CREATE TABLE ADMIN (
    ADMIN_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADMIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Πίνακας Υπαλλήλων
DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    SALARY DECIMAL(10,2) NOT NULL,
    DAYOFF BOOLEAN DEFAULT 0,
    PRIMARY KEY (EMPLOYEE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Πίνακας Δωματίων
DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
    ROOM_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ROOM_NUMBER VARCHAR(10) NOT NULL UNIQUE,
    ROOM_TYPE ENUM('Single', 'Double', 'Suite') NOT NULL,
    PRICE_PER_NIGHT DECIMAL(10,2) NOT NULL,
    STATUS ENUM('Available', 'Booked', 'Under Maintenance') DEFAULT 'Available',
    PRIMARY KEY (ROOM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Πίνακας Κρατήσεων
DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION (
    RESERVATION_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID SMALLINT UNSIGNED NOT NULL,
    ROOM_ID SMALLINT UNSIGNED NOT NULL,
    CHECK_IN DATE NOT NULL,
    CHECK_OUT DATE NOT NULL,
    STATUS ENUM('Confirmed', 'Cancelled', 'Completed') DEFAULT 'Confirmed',
    PRIMARY KEY (RESERVATION_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE,
    FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

